language: node_js
node_js:
  - "0.12"
before_install:
  - "npm install -g mocha"
  - "npm install -g chai"
  - "npm install -g istanbul"
  - "npm install -g codeclimate-test-reporter"
  - "npm install -g grunt"
  - "npm install -g grunt-cli"
  - "npm install -g grunt-init"
  - "npm install -g grunt-shell"
  - "npm install -g grunt-mocha-istanbul"
